server:
  servlet:
    application-display-name: "Stock Manager API"
    context-path: "/api/v1"

spring:
  application:
    name: "Stock Manager API"
  jpa:
    open-in-view: "false"
    generate-ddl: "false"
    hibernate:
      ddl-auto: "none"
    show-sql: "true"
    properties:
      javax:
        persistence:
          schema-generation:
            # create-source: "metadata"
            scripts:
                # action: "create"
                # create-target: "create-schema.sql"
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: "true"
        format_sql: "true"
  datasource:
    name: "stock-manager-api-ds"
    url: "jdbc:postgresql://localhost:5432/stock-manager-api-db"
    username: "postgres"
    password: "postgres"
