server:
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: "Stock Manager API"
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: "jdbc:h2:mem:stock-manager-api-db"
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: "/h2-console"
